spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db:3307/restSpringTCC
    username: root
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false